-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'KYC_INITIATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'KYC_DOCUMENT_UPLOADED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'KYC_DOCUMENT_APPROVED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'KYC_DOCUMENT_REJECTED';
